version: '3'


volumes:
  cache:
    driver: local


services:
  app:
    build:
      context: .
    container_name: bamper
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bamper
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8080:8080'
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bamper
  redis:
    image: redis:7.2-rc-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass Z2ZqbmdpbWttNHI0MzFkcwo=
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
