spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: Z2ZqbmdpbWttNHI0MzFkcwo=
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bamper?currentSchema=bamper
    username: postgres
    password: root
  jpa:
    showSql: true
  sql:
    init:
      mode: never
      continue-on-error: false
      #      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
security:
  jwt:
    secret: ZHNhZHNhZGthc2RrbWFza2RtYXNrZG1hc2ttZGthc2RrYXNtZG1hc2tkcw==
    access: 3600000
    refresh: 2592000000