spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    showSql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default_schema: ${POSTGRES_SCHEMA}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    confirmLink: ${MAIL_CONFIRMATION_LINK}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 2592000000
    refresh: 2592000000
minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
springdoc:
  override-with-generic-response: false
yandex:
  geocoder:
    key: ${GEOCODER_API_KEY}
    url: https://geocode-maps.yandex.ru/1.x/?apikey=${GEOCODER_API_KEY}&geocode=
    format: format=json
